easy_admin:
  entities:
    Child:
      class: App\Entity\Child
      list:
        fields:
          - { property: 'id', label: 'ID Enfant', type: 'integer' }
          - { property: 'client_id', label: 'ID Parent', type: 'integer' }
          - { property: 'name', label: 'Prenom', type: 'string' }
          - { property: 'lastname', label: 'Nom', type: 'string' }
          - { property: 'age', label: 'Age', type: 'integer' }
          - { property: 'info', label: 'Info', type: 'string' }
          - { property: 'gender', label: 'Genre', type: 'string' }
      form:
        fields:
          - { property: 'client_id', label: 'ID Parent' }
          - { property: 'name', label: 'Prenom' }
          - { property: 'lastname', label: 'Nom' }
          - { property: 'age', label: 'Age' }
          - { property: 'info', label: 'Info' }
          - { property: 'gender', label: 'Genre' }