easy_admin:
  entities:
    Contact:
      class: App\Entity\Contact
      list:
        fields:
          - { property: 'id', label: 'ID Client', type: 'integer' }
          - { property: 'name', label: 'Nom', type: 'string'}
          - { property: 'phone', label: 'Telephone', type: 'string' }
          - { property: 'relation', label: 'Relation', type: 'string' }
          - { property: 'children_id', label: 'ID Enfant', type: 'string'}
      actions:
        - { name: 'edit', icon: 'pencil', label: false ,  css_class: 'btn btn-secondary' }
        - { name: 'delete', icon: 'trash', label: false , css_class: 'btn btn-danger' }
        - { name: 'new', icon: 'plus', label: false , css_class: 'btn btn-primary' }
      form:
        fields:
          - { property: 'name', label: 'Nom'}
          - { property: 'phone', label: 'Telephone'}
          - { property: 'relation', label: 'Relation' }
          - { property: 'child', label: 'ID Enfant'}
